id: P007124
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG478
  title: རྨ་ལྷོའི་ཚན་རྩལ་ཀློག་དེབ་
  author: ''
  volumes:
    c504cf1a3ce64eb6ad32f1d74c1b610a:
      image_group_id: I1KG482
      title: ''
      volume_number: 1
      total_pages: 320
ebook_metadata:
  title: རྨ་ལྷོའི་ཚན་རྩལ་ཀློག་དེབ་
  author: ''
  sku: P007124
  cover: cover.jpg
  layers:
  - pagination
