id: P007124
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 12:43:18.026546
source_metadata:
  id: bdr:W1KG478
  title: རྨ་ལྷོའི་ཚན་རྩལ་ཀློག་དེབ་
  author: ''
  volumes:
    0e47a057a9cc49858906cda9f685a533:
      image_group_id: I1KG482
      title: Volume 1 of rma lho'i tshan rtsal klog deb
      volume_number: 1
      total_pages: 320
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
